/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Control.*;
import java.sql.*;
import java.text.*;
import java.util.*;
import java.util.logging.*;
import javax.swing.*;
import javax.swing.table.*;
import model.*;

public class GUI_transaksi extends javax.swing.JFrame {

    private Control control;
    private ArrayList<DetailTransaksi> arrdetailtran;
    private Integer harga;
    
    public GUI_transaksi() throws SQLException {
        initComponents();
        control = new Control();
        arrdetailtran = new ArrayList<>();
        harga =0;
        TFharga.disable();
        showCBbahan();
        showCBwarna();
        showTBwarna();
        showHarga();
        showTBtransaksi();
    }
    
    public void showCBbahan() throws SQLException{
        DefaultComboBoxModel dcbbahan = new DefaultComboBoxModel();
        for(StockBahan SB : control.getDataBahan()){
            dcbbahan.addElement(SB.getNama_bahan());
        }
       CBbahan.removeAllItems();
       CBbahan.setModel(dcbbahan);
    }
    
    public void showCBwarna()throws SQLException{
        DefaultComboBoxModel dcbwarna = new DefaultComboBoxModel();
        for(StockWarna SW : control.getDataWarna()){
                dcbwarna.addElement(SW.getWarna() + " (" + SW.getJeniswarna().getWarna_bahan()+")");           
        }
        CBwarna.removeAllItems();
        CBwarna.setModel(dcbwarna);
    }
    
    public void showTBwarna() throws SQLException{
        DefaultTableModel tbkeran = new DefaultTableModel(new String[]{
            "Warna", "Harga Warna", "Jenis Warna", "Jumlah Bahan"},0);
            for(DetailTransaksi dt : arrdetailtran){
                tbkeran.addRow(new String[]{dt.getStockWarna().getWarna().toString(), dt.getStockWarna().getHarga_warna().toString(), dt.getStockWarna().getJeniswarna().getWarna_bahan().toString(), dt.getJumlah().toString()
                });
            }
            TBLkeranjang.setModel(tbkeran);
    }
    
    public void showHarga(){
        TFharga.setText(harga.toString());
    }
    
    public void showTBtransaksi() throws SQLException{
        DefaultTableModel dtbtran = new DefaultTableModel(new String[]{"Bahan","Tanggal Transaksi","Total"},0);
        for(Transaksi T : control.getDataTransaksi()){
            dtbtran.addRow(new String[]{ T.getStockBahan().getNama_bahan(), T.getTgl_transaksi().toString(), T.getTotal_harga().toString()});
        }
        TBLtransaksi.setModel(dtbtran);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CBbahan = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TFjumlah = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CBwarna = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBLkeranjang = new javax.swing.JTable();
        BTNtambahwarna = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        TFharga = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TBLtransaksi = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        TFtgl = new javax.swing.JTextField();
        BTNmasuktransaksi = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CBbahan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("PEMESANAN");

        jLabel2.setText("Bahan");

        jLabel3.setText("Jumlah");

        jLabel4.setText("Warna");

        CBwarna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CBwarna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBwarnaActionPerformed(evt);
            }
        });

        TBLkeranjang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TBLkeranjang);

        BTNtambahwarna.setText("Tambah Warna");
        BTNtambahwarna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNtambahwarnaActionPerformed(evt);
            }
        });

        jLabel5.setText("Harga");

        TFharga.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("TRANSAKSI");

        TBLtransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(TBLtransaksi);

        jLabel8.setText("Tgl Transaksi");

        BTNmasuktransaksi.setText("Masuk ke transaksi");
        BTNmasuktransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNmasuktransaksiActionPerformed(evt);
            }
        });

        jButton2.setText("Detail");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel5)
                        .addGap(32, 32, 32)
                        .addComponent(TFharga, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BTNtambahwarna)
                        .addGap(98, 98, 98))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CBbahan, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TFjumlah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CBwarna, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(BTNmasuktransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(48, 48, 48)
                                        .addComponent(TFtgl, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(27, 27, 27))))
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(141, 141, 141))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CBbahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(TFtgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTNmasuktransaksi)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(CBwarna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(BTNtambahwarna)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jButton1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TFharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(703, 590));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CBwarnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBwarnaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBwarnaActionPerformed

    private void BTNtambahwarnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNtambahwarnaActionPerformed
        try{
            DetailTransaksi dT = new DetailTransaksi();
            dT.setStockWarna(control.getDataWarna().get(CBwarna.getSelectedIndex()));
            dT.setJumlah(Integer.parseInt(TFjumlah.getText()));
            if(arrdetailtran.isEmpty()){
                
                    harga += control.getDataBahan().get(CBbahan.getSelectedIndex()).getHarga_satuan() * Integer.parseInt(TFjumlah.getText()) + control.getDataWarna().get(CBwarna.getSelectedIndex()).getHarga_warna() * Integer.parseInt(TFjumlah.getText());
                }else{
                    harga += control.getDataWarna().get(CBwarna.getSelectedIndex()).getHarga_warna() * Integer.parseInt(TFjumlah.getText());
                }  
            showHarga();
            arrdetailtran.add(dT);
            showTBwarna();
            //TFjumlah.setText("");
            CBbahan.disable();
            TFjumlah.disable();
        }catch(SQLException exx){
            
        }
    }//GEN-LAST:event_BTNtambahwarnaActionPerformed

    private void BTNmasuktransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNmasuktransaksiActionPerformed
        CBbahan.enable();
        TFjumlah.enable();
        
        Transaksi tran = new Transaksi();
        try{
            tran.setTgl_transaksi(new SimpleDateFormat("dd/MM/yyy").parse(TFtgl.getText()));
            tran.setStockBahan(control.getDataBahan().get(CBbahan.getSelectedIndex()));
            tran.setTotal_harga(harga);
            tran.setJumlah_bahan(Integer.parseInt(TFjumlah.getText()));
            tran.setArrdetail(arrdetailtran);
            control.insertTransaksi(tran);
            showTBtransaksi();
            arrdetailtran = new ArrayList<>();
            showTBwarna();
            TFtgl.setText("");
            harga=0;
            showHarga();
            TFjumlah.setText("");
        } catch (ParseException ex) {
            Logger.getLogger(GUI_transaksi.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(GUI_transaksi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BTNmasuktransaksiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new GUI_login().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            Transaksi transaksi = control.getDataTransaksi().get(TBLtransaksi.getSelectedRow());
            String detail = "===SELAMAT DATANG DI MY SABLON===\n" +
            "Tanggal Transaksi  : " +transaksi.getTgl_transaksi()+ "\n" +
            "Nama Bahan         : " +transaksi.getStockBahan().getNama_bahan()+ "\n" +
            "Harga Satuan Bahan : " +transaksi.getStockBahan().getHarga_satuan()+ "\n" +
            "Jumlah Bahan       : " +transaksi.getJumlah_bahan()+ "\n" +
            "Total Harga        : " +transaksi.getTotal_harga()+ "\n";
            ArrayList<DetailTransaksi> detaill = transaksi.getArrdetail();
            System.out.println(detaill.size());
            for (int i = 0; i < detaill.size(); i++) {
                detail += "\nWarna ke         : " +(i+1)+ "\n" +
                "Nama Warna          : " +detaill.get(i).getStockWarna().getWarna()+ "\n" +
                "Harga Satuan Warna  : " +detaill.get(i).getStockWarna().getHarga_warna()+ "\n" +
                "Jenis Warna         : " +detaill.get(i).getStockWarna().getJeniswarna().getWarna_bahan() + "\n";
            }
            JOptionPane.showMessageDialog(this, detail);

        } catch (SQLException ex) {
            Logger.getLogger(GUI_transaksi.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNmasuktransaksi;
    private javax.swing.JButton BTNtambahwarna;
    private javax.swing.JComboBox<String> CBbahan;
    private javax.swing.JComboBox<String> CBwarna;
    private javax.swing.JTable TBLkeranjang;
    private javax.swing.JTable TBLtransaksi;
    private javax.swing.JTextField TFharga;
    private javax.swing.JTextField TFjumlah;
    private javax.swing.JTextField TFtgl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
