/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Control.*;
import java.sql.*;
import java.text.*;
import java.util.*;
import java.util.logging.*;
import javax.swing.*;
import javax.swing.table.*;
import model.*;

public class GUI_stockBahan extends javax.swing.JFrame {

    private Control control;
    
    public GUI_stockBahan() throws SQLException {
        initComponents();
        control = new Control();
        showTBLstockBahan();
    }
    
    public void showTBLstockBahan() throws SQLException{
        DefaultTableModel dtsb = new DefaultTableModel(new String[]{"Nama Bahan", "Stock", "Harga Satuan"},0);
        for(StockBahan sb : control.getDataBahan()){
            dtsb.addRow(new String[]{sb.getNama_bahan().toString(), sb.getStok().toString(), sb.getHarga_satuan().toString()});
        }
        TBLstockbahan.setModel(dtsb);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBLstockbahan = new javax.swing.JTable();
        BTNinsert = new javax.swing.JButton();
        BTNupdate = new javax.swing.JButton();
        BTNdelete = new javax.swing.JButton();
        BTNkembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("STOCK BAHAN");

        TBLstockbahan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TBLstockbahan);

        BTNinsert.setText("Insert");
        BTNinsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNinsertActionPerformed(evt);
            }
        });

        BTNupdate.setText("Update");
        BTNupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNupdateActionPerformed(evt);
            }
        });

        BTNdelete.setText("Delete");
        BTNdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNdeleteActionPerformed(evt);
            }
        });

        BTNkembali.setText("Kembali");
        BTNkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNkembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(BTNinsert)
                .addGap(26, 26, 26)
                .addComponent(BTNupdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTNdelete)
                .addGap(18, 18, 18)
                .addComponent(BTNkembali)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNinsert)
                    .addComponent(BTNupdate)
                    .addComponent(BTNdelete)
                    .addComponent(BTNkembali))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(418, 449));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BTNinsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNinsertActionPerformed
        try {
            StockBahan SB = new StockBahan();
            String bahan = JOptionPane.showInputDialog("Nama Bahan");
            int stock = Integer.parseInt(JOptionPane.showInputDialog("Stock"));
            int harga = Integer.parseInt(JOptionPane.showInputDialog("Harga Satuan"));
            SB.setNama_bahan(bahan);
            SB.setStok(stock);
            SB.setHarga_satuan(harga);
            control.insertStockBahan(SB);
            showTBLstockBahan();
            bahan="";
            stock=0;
            harga=0;
        } catch (SQLException ex) {
            Logger.getLogger(GUI_stockBahan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BTNinsertActionPerformed

    private void BTNupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNupdateActionPerformed
        try {
            StockBahan stockBahan = control.getDataBahan().get(TBLstockbahan.getSelectedRow());
            String bahan = JOptionPane.showInputDialog("Nama Bahan");
            int stock = Integer.parseInt(JOptionPane.showInputDialog("Stock"));
            int harga = Integer.parseInt(JOptionPane.showInputDialog("Harga Satuan"));
            
            control.updateStockBahan(stockBahan, bahan, stock, harga);
            showTBLstockBahan();
        } catch (SQLException ex) {
            Logger.getLogger(GUI_stockBahan.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            
    }//GEN-LAST:event_BTNupdateActionPerformed

    private void BTNdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNdeleteActionPerformed
        try {
            StockBahan stockBahan = control.getDataBahan().get(TBLstockbahan.getSelectedRow());
            control.deleteStockBahan(stockBahan);
            showTBLstockBahan();
        } catch (SQLException ex) {
            Logger.getLogger(GUI_stockBahan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BTNdeleteActionPerformed

    private void BTNkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNkembaliActionPerformed
        new GUI_menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_BTNkembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_stockBahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_stockBahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_stockBahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_stockBahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new GUI_stockBahan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNdelete;
    private javax.swing.JButton BTNinsert;
    private javax.swing.JButton BTNkembali;
    private javax.swing.JButton BTNupdate;
    private javax.swing.JTable TBLstockbahan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
